server:
  port: 8086

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/mankind
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/mankind/protocol/openid-connect/certs

# SMS Gateway Configuration (e.g., Twilio)
sms:
  twilio:
    account-sid: ${SMS_ACCOUNT_SID:your-account-sid}
    auth-token: ${SMS_AUTH_TOKEN:your-auth-token}
    phone-number: ${SMS_PHONE_NUMBER:your-twilio-phone-number}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    mail:
      enabled: false

logging:
  level:
    com.mankind.notification_service: INFO
    org.springframework.mail: DEBUG
