server:
  port: 8086

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?connectTimeout=${DB_CONNECT_TIMEOUT}&socketTimeout=${DB_SOCKET_TIMEOUT}&useSSL=${DB_USE_SSL}&allowPublicKeyRetrieval=${DB_ALLOW_PUBLIC_KEY_RETRIEVAL}&serverTimezone=${DB_SERVER_TIMEZONE}&autoReconnect=${DB_AUTO_RECONNECT}&failOverReadOnly=${DB_FAIL_OVER_READ_ONLY}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: ${DB_HIKARI_CONNECTION_TIMEOUT:20000}
      maximum-pool-size: ${DB_HIKARI_MAX_POOL_SIZE:2}
      minimum-idle: ${DB_HIKARI_MIN_IDLE:0}
      idle-timeout: ${DB_HIKARI_IDLE_TIMEOUT:120000}
      max-lifetime: ${DB_HIKARI_MAX_LIFETIME:300000}
      leak-detection-threshold: ${DB_HIKARI_LEAK_DETECTION_THRESHOLD:30000}
      connection-test-query: SELECT 1
      validation-timeout: 5000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: false
        format_sql: true
        current_session_context_class: thread
        transaction:
          auto_commit: true
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/mankind
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/mankind/protocol/openid-connect/certs

# SMS Gateway Configuration (e.g., Twilio)
sms:
  twilio:
    account-sid: ${SMS_ACCOUNT_SID:your-account-sid}
    auth-token: ${SMS_AUTH_TOKEN:your-auth-token}
    phone-number: ${SMS_PHONE_NUMBER:your-twilio-phone-number}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    mail:
      enabled: false

logging:
  level:
    com.mankind.notification_service: INFO
    org.springframework.mail: DEBUG
