services:
  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
      args:
        MAVEN_OPTS: "-Xmx512m -XX:MaxMetaspaceSize=256m"
    container_name: mankind-product-service
    ports:
      - "8080:8080"
    env_file:
      - product-service/.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:MaxMetaspaceSize=256m
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
    networks:
      - mankind-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
      args:
        MAVEN_OPTS: "-Xmx512m -XX:MaxMetaspaceSize=256m"
    container_name: mankind-user-service
    ports:
      - "8081:8080"
    env_file:
      - user-service/.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:MaxMetaspaceSize=256m
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
    networks:
      - mankind-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
      args:
        MAVEN_OPTS: "-Xmx512m -XX:MaxMetaspaceSize=256m"
    container_name: mankind-cart-service
    ports:
      - "8082:8080"
    env_file:
      - cart-service/.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:MaxMetaspaceSize=256m
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
    networks:
      - mankind-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  wishlist-service:
    build:
      context: .
      dockerfile: wishlist-service/Dockerfile
      args:
        MAVEN_OPTS: "-Xmx512m -XX:MaxMetaspaceSize=256m"
    container_name: mankind-wishlist-service
    ports:
      - "8083:8080"
    env_file:
      - wishlist-service/.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:MaxMetaspaceSize=256m
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
    networks:
      - mankind-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  notification-service:
      build:
        context: .
        dockerfile: notification-service/Dockerfile
        args:
          MAVEN_OPTS: "-Xmx512m -XX:MaxMetaspaceSize=256m"
      container_name: mankind-notification-service
      ports:
        - "8084:8080"
      env_file:
        - notification-service/.env
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - JAVA_OPTS=-Xms256m -Xmx512m -XX:MaxMetaspaceSize=256m
      deploy:
        resources:
          limits:
            memory: 768M
          reservations:
            memory: 512M
      networks:
        - mankind-network
      healthcheck:
        test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s
      restart: unless-stopped


networks:
  mankind-network:
    driver: bridge 