spring:
  application:
    name: mankind-gateway-service

  cloud:
    gateway:
      forwarded:
        enabled: false
      discovery:
        locator:
          enabled: false

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: GET,POST,PUT,DELETE,OPTIONS

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin,RETAIN_UNIQUE
        - DedupeResponseHeader=Access-Control-Allow-Credentials,RETAIN_UNIQUE

      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          
        - id: products
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/products/**
          
        - id: cart
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/cart/**
          
        - id: wishlist
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/wishlist/**
          

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/mankind

server:
  port: 8085

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 100
        limit-refresh-period: 1m
        timeout-duration: 0
    instances:
      apiGateway:
        base-config: default
