server:
  port: 8081
keycloak:
  auth-server-url: http://localhost:8180
  realm: mankind
  # admin user
  admin-user: admin
  admin-password: admin
  admin-realm: master
  admin-client-id: admin-cli
  client-secret: 5bc3VyTOCv8OIVwygE36ZwZhbqMnlu0X
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?connectTimeout=${DB_CONNECT_TIMEOUT}&socketTimeout=${DB_SOCKET_TIMEOUT}&useSSL=${DB_USE_SSL}&allowPublicKeyRetrieval=${DB_ALLOW_PUBLIC_KEY_RETRIEVAL}&serverTimezone=${DB_SERVER_TIMEZONE}&autoReconnect=${DB_AUTO_RECONNECT}&failOverReadOnly=${DB_FAIL_OVER_READ_ONLY}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: ${DB_HIKARI_CONNECTION_TIMEOUT:60000}
      maximum-pool-size: ${DB_HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_HIKARI_MIN_IDLE:5}
      idle-timeout: ${DB_HIKARI_IDLE_TIMEOUT:300000}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/mankind/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: false
        format_sql: true
        current_session_context_class: thread
        transaction:
          auto_commit: true
  profiles:
    active: dev
logging:
  level:
    org.springframework.security: DEBUG
jwt:
  secret: a-sample-long-secret-key-that-is-over-32-characters

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  packages-to-scan: com.mankind.mankindmatrixuserservice.controller

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
